# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ROSTopic/topic.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class topic(genpy.Message):
  _md5sum = "8da47db7c1d4d80b9057432e547605d1"
  _type = "ROSTopic/topic"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int64 usia
float64 tinggi
string nama
bool kehadiran
float64 komponenX
float64 komponenY
float64 komponenZ
float64 magnitude"""
  __slots__ = ['usia','tinggi','nama','kehadiran','komponenX','komponenY','komponenZ','magnitude']
  _slot_types = ['int64','float64','string','bool','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       usia,tinggi,nama,kehadiran,komponenX,komponenY,komponenZ,magnitude

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(topic, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.usia is None:
        self.usia = 0
      if self.tinggi is None:
        self.tinggi = 0.
      if self.nama is None:
        self.nama = ''
      if self.kehadiran is None:
        self.kehadiran = False
      if self.komponenX is None:
        self.komponenX = 0.
      if self.komponenY is None:
        self.komponenY = 0.
      if self.komponenZ is None:
        self.komponenZ = 0.
      if self.magnitude is None:
        self.magnitude = 0.
    else:
      self.usia = 0
      self.tinggi = 0.
      self.nama = ''
      self.kehadiran = False
      self.komponenX = 0.
      self.komponenY = 0.
      self.komponenZ = 0.
      self.magnitude = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_qd().pack(_x.usia, _x.tinggi))
      _x = self.nama
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B4d().pack(_x.kehadiran, _x.komponenX, _x.komponenY, _x.komponenZ, _x.magnitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.usia, _x.tinggi,) = _get_struct_qd().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.nama = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.nama = str[start:end]
      _x = self
      start = end
      end += 33
      (_x.kehadiran, _x.komponenX, _x.komponenY, _x.komponenZ, _x.magnitude,) = _get_struct_B4d().unpack(str[start:end])
      self.kehadiran = bool(self.kehadiran)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_qd().pack(_x.usia, _x.tinggi))
      _x = self.nama
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B4d().pack(_x.kehadiran, _x.komponenX, _x.komponenY, _x.komponenZ, _x.magnitude))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.usia, _x.tinggi,) = _get_struct_qd().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.nama = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.nama = str[start:end]
      _x = self
      start = end
      end += 33
      (_x.kehadiran, _x.komponenX, _x.komponenY, _x.komponenZ, _x.magnitude,) = _get_struct_B4d().unpack(str[start:end])
      self.kehadiran = bool(self.kehadiran)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B4d = None
def _get_struct_B4d():
    global _struct_B4d
    if _struct_B4d is None:
        _struct_B4d = struct.Struct("<B4d")
    return _struct_B4d
_struct_qd = None
def _get_struct_qd():
    global _struct_qd
    if _struct_qd is None:
        _struct_qd = struct.Struct("<qd")
    return _struct_qd
